baseURL = "https://lucapanofsky.github.io/unBl0g/"
languageCode = "it"
title = "un bl0g"

[permalinks]
posts = "posts/:year/:month/:slug/"
year = "/posts/:slug/"
month = "/posts/:slug/"

[taxonomies]
year = "year"
month = "month"
tag = "tags"
category = "categories"
